#                            __ _ _
#                           / _(_) |
#       _____ __  _ __ ___ | |_ _| | ___
#      |_  / '_ \| '__/ _ \|  _| | |/ _ \
#     _ / /| |_) | | | (_) | | | | |  __/
#    (_)___| .__/|_|  \___/|_| |_|_|\___|
#          | |
#          |_|
#

# Source Prezto
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Editors
export EDITOR='/usr/local/bin/nvim'
export VISUAL='/usr/local/bin/nvim'
export PAGER='/usr/bin/less'

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

# Locale langage
export LANG=ja_JP.UTF-8
export LC_TYPE=ja_JP.UTF-8

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set colors
export TERM=xterm-256color
autoload -Uz colors
colors

# Complement
autoload -Uz compinit
compinit

# Auto change dir
setopt auto_cd

# Fix typo command
setopt correct

# history settings
export HISTFILE=${HOME}/.zhistory
export HISTSIZE=10000
export SAVEHIST=100000
setopt hist_ignore_dups
setopt EXTENDED_HISTORY

# Enable cdr, add-zsh-hook
autoload -Uz chpwd_recent_dirs cdr add-zsh-hook
add-zsh-hook chpwd chpwd_recent_dirs

# Setting cdr
zstyle ':completion:*' recent-dirs-insert both
zstyle ':chpwd:*' recent-dirs-max 500
zstyle ':chpwd:*' recent-dirs-default true
zstyle ':chpwd:*' recent-dirs-file "$HOME/.cache/chpwd-recent-dirs"
zstyle ':chpwd:*' recent-dirs-pushd true
