# require deoplete
[[plugins]]
repo = 'roxma/nvim-yarp'

# require deoplete
# 以下コマンドの実行が必要(環境に応じてpathに気をつける)
# /usr/local/bin/pip3 install -U neovim
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

# snippet 補完
[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
    let g:deoplete#enable_at_startup = 1
    inoremap <expr><tab> pumvisible() ? "\<C-n>" :
    \     neosnippet#expandable_or_jumpable() ?
    \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1
depends = [ 'nvim-yarp', 'vim-hug-neovim-rpc' ]

# snippet
[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

# python
[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = ['python']

[[plugins]]
repo = 'hdima/python-syntax'
on_ft = ['python']

# Golang
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = '''
    autocmd FileType go set autowrite
    let g:go_highlight_functions = 1
    let g:go_highlight_methods = 1
    let g:go_highlight_structs = 1

    let mapleader = "\<Space>"
    au FileType go nmap <leader>s <Plug>(go-def-split)
    au FileType go nmap <leader>v <Plug>(go-def-vertical)
'''

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = ['go']
hook_source = '''
    let g:deoplete#sources#go#gocode_binary = $GOPATH . '/bin/gocode'
'''

# yaml
[[plugins]]
repo = 'chase/vim-ansible-yaml'
on_ft = ['yml']

# js
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']

[[plugins]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript']

[[plugins]]
repo = 'othree/javascript-libraries-syntax.vim'
on_ft = ['javascript']

# Vue.js
#[[plugins]]
#repo = 'posva/vim-vue'
#on_ft = ['vue']

# html
[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

# css
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css']

# ruby on rails
[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['rb']

[[plugins]]
repo = 'basyura/unite-rails'
on_ft = ['rb']

#json
[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_add = '''
    let g:vim_json_syntax_conceal = 0
'''

repo = 'rhysd/vim-fixjson'
on_ft = ['json']

# toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# markdown
#[[plugins]]
#repo = 'plasticboy/vim-markdown'
#on_ft = ['markdown', 'md']

#[[plugins]]
#repo = 'kannokanno/previm'
#on_ft = ['markdown', 'md']

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown', 'md']
