# dein require
[[plugins]]
repo = 'Shougo/dein.vim'

# vim 非同期処理用
[[plugins]]
repo = 'Shougo/vimproc.vim'

# snippet
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# context カーソル位置のコンテキストのftを判定
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# context カーソル位置のコンテキストに合わせてftを切り替える
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

# context color schema
[[plugins]]
repo = 'w0ng/vim-hybrid'
#hook_add = '''
#    set background=dark
#'''

# save vim session
[[plugins]]
repo = 'tpope/vim-obsession'

# Syntastic check
[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
    let g:ale_sign_column_always = 1
    let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
'''

# Statusline design
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {
    \    'colorscheme': 'powerline',
    \    'active': {
    \        'left': [
    \            [ 'mode', 'paste' ],
    \            [ 'readonly', 'filename', 'modified', 'ale' ]
    \        ],
    \        'right': [
    \            [ 'lineinfo' ],
    \            [ 'percent' ],
    \            [ 'fileformat', 'fileencoding', 'filetype' ]
    \        ]
    \    },
    \    'component_function': {
    \        'ale': 'ALEGetStatusLine'
    \    },
    \    'separator': {
    \        'left': "\ue0b0",
    \        'right': "\ue0b2"
    \    },
    \    'subseparator': {
    \        'left': "\ue0b1",
    \        'right': "\ue0b3"
    \    }
    \ }
    let g:lightline.tabline = {
    \    'left': [ [ 'tabs' ] ],
    \    'right': [ [ 'close' ] ]
    \ }
'''

# NERDTree
# Usage: C-n
[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    let g:NERDTreeDirArrows = 1
    let g:NERDTreeDirArrowExpandable  = '→'
    let g:NERDTreeDirArrowCollapsible = '↓'
    let g:NERDTreeShowHidden = 1
    nnoremap <silent> <C-n> :NERDTreeToggle<CR>
'''

# NERDTree display git status
[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

# 左端にgit diff iconを表示
[[plugins]]
repo = 'airblade/vim-gitgutter'

# vim window resize
# usage: <C-x> start, h, j, k, l resize
[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
    let g:winresizer_start_key = '<C-x>'
'''

# file selecter
# usage: <C-p>
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

# if, funcのendを補完
[[plugins]]
repo = 'tpope/vim-endwise'

# Comment in/out
# Usage: Visual mode + gc
[[plugins]]
repo = 'tpope/vim-commentary'
