---
- name: Unlink fish function file
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/fish/functions/{{ item }}"
    state: absent
  loop: "{{ shell_fish_function }}"

- name: Unlink starship config file
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/starship.toml"
    state: absent

- name: Create fish config directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/fish/functions"
    state: directory

- name: Install fisher
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish"
    dest: "{{ ansible_env.HOME }}/.config/fish/functions/fisher.fish"
    validate_certs: true

- name: Install plugins
  ansible.builtin.shell:
    cmd: |
      fish -c "fisher install {{ item }}"
  loop:
    - jethrokuan/fzf
    - jethrokuan/z
    - evanlucas/fish-kubectl-completions

- name: Set fish functions
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/dotfiles/roles/shell/files/functions/{{ item }}"
    path: "{{ ansible_env.HOME }}/.config/fish/functions/{{ item }}"
    state: link
    force: true
  loop: "{{ shell_fish_function }}"

- name: Set starship config
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/dotfiles/roles/shell/files/starship.toml"
    path: ~/.config/starship.toml
    state: link
    force: true

- name: Set fish config files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: true
  loop: "{{ shell_fish_config }}"

- name: Append git-delta config to ~/.gitconfig
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.HOME }}/.gitconfig"
    block: |
      [core]
      pager = delta

      [interactive]
      diffFilter = delta --color-only --features=interactive

      [delta]
      features = decorations

      side-by-side = true
      line-numbers-left-format = ""
      line-numbers-right-format = "│ "

      [delta "interactive"]
      keep-plus-minus-markers = false

      [delta "decorations"]
      commit-decoration-style = blue ol
      commit-style = raw
      file-style = omit
      hunk-header-decoration-style = blue box
      hunk-header-file-style = red
      hunk-header-line-number-style = "#067a00"
      hunk-header-style = file line-number syntax
    marker: "# ANSIBLE MANAGED BLOCK: git-delta"
    insertafter: EOF
    state: present

- name: Search shell path
  ansible.builtin.shell:
    cmd: |
      /usr/bin/which {{ SHELL }}
  register: shell_path
  failed_when: false

- name: Check shells file
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      /bin/cat /etc/shells | /usr/bin/grep {{ shell_path.stdout }}
  register: chk_shell
  failed_when: false

- name: Append shells
  ansible.builtin.lineinfile:
    dest: /etc/shells
    line: "{{ shell_path.stdout }}"
    regexp: "{{ shell_path.stdout }}"
    insertafter: EOF
  when: chk_shell.rc != 0
  become: true

- name: Change login shell
  ansible.builtin.shell:
    cmd: |
      /usr/bin/chpass -s {{ shell_path.stdout }}
  when: chk_shell.rc != 0
  register: result
  until: result.rc == 0
