---
- name: Search path zsh
  shell: >
    /usr/bin/which zsh
  register: which_zsh
  ignore_errors: True

- name: Check shells file
  shell: >
    /bin/cat /etc/shells | /usr/bin/grep "{{which_zsh.stdout}}"
  register: grep_shells
  ignore_errors: True

- block:

  - name: Append shells
    lineinfile:
        dest: /etc/shells
        line: "{{ which_zsh.stdout }}"
        regexp: "{{ which_zsh.stdout }}"
        insertafter: EOF

  - name: Change login shell
    shell: >
      /usr/bin/chpass -s {{which_zsh.stdout}}
    register: result
    until: result.rc == 0

  when: grep_shells.rc != 0
  become: true
