---
- name: Add plugin
  shell: >
    asdf plugin-add {{ plugin_list_item }}
  ignore_errors: True
  loop: "{{ plugin_list }}"
  loop_control:
    loop_var: plugin_list_item

- name: Install latest version
  shell: >
    asdf install {{ plugin_list_item }} latest
  loop: "{{ plugin_list }}"
  loop_control:
    loop_var: plugin_list_item

