---
- name: Clone prezto repo
  git:
    repo: "https://github.com/sorin-ionescu/prezto.git"
    dest: "{{ ansible_env.HOME }}/.zprezto"
    recursive: yes
    force: yes

- name: Symbolic link zsh config
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: yes
  loop:
    - src: "{{ ansible_env.HOME }}/dotfiles/zsh/zshrc"
      dest: "{{ ansible_env.HOME }}/.zshrc"
    - src: "{{ ansible_env.HOME }}/dotfiles/zsh/zprofile"
      dest: "{{ ansible_env.HOME }}/.zprofile"
    - src: "{{ ansible_env.HOME }}/dotfiles/zsh/zpreztorc"
      dest: "{{ ansible_env.HOME }}/.zpreztorc"
    - src: "{{ ansible_env.HOME }}/dotfiles/zsh/p10k.zsh"
      dest: "{{ ansible_env.HOME }}/.p10k.zsh"
