# require
[[plugins]]
repo = 'Shougo/dein.vim'

# require (not neovim)
[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

# require (not neovim)
[[plugins]]
repo = 'roxma/nvim-yarp'

# vim 非同期処理用
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# context カーソル位置のコンテキストのftを判定
[[plugins]]
repo = 'Shougo/context_filetype.vim'

# context カーソル位置のコンテキストに合わせてftを切り替える
[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

# context color schema
[[plugins]]
repo = 'w0ng/vim-hybrid'
#hook_add = '''
#    set background=dark
#'''

# save vim session
[[plugins]]
repo = 'tpope/vim-obsession'

# ( ) coloring
[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
    let g:rainbow_active = 1
'''

# Statusline design
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    function! AbsolutePath()
        let path = expand("%F")
        if path == ""
            return '[No Name]'
        elseif strlen(path) > 32
            return pathshorten(path)
        else
            return path
        endif
    endfunction

    let g:lightline = {
    \    'colorscheme': 'powerline',
    \    'active': {
    \        'left': [
    \            [ 'mode', 'paste' ],
    \            [ 'readonly', 'filename', 'modified' ],
    \            [ 'linter_checking', 'linter_errors', 'linter_warnings', 'linter_ok' ]
    \        ],
    \        'right': [
    \            [ 'lineinfo' ],
    \            [ 'percent' ],
    \            [ 'fileformat', 'fileencoding', 'filetype' ]
    \        ]
    \    },
    \    'component_function': {
    \        'filename': 'AbsolutePath'
    \    },
    \    'separator': {
    \        'left': "\ue0b0",
    \        'right': "\ue0b2"
    \    },
    \    'subseparator': {
    \        'left': "\ue0b1",
    \        'right': "\ue0b3"
    \    }
    \ }

    function! LightlineTabFilename(n) abort
        let buflist = tabpagebuflist(a:n)
        let winnr = tabpagewinnr(a:n)
        let _ = pathshorten(expand('#'.buflist[winnr - 1].':f'))
        return _ !=# '' ? _ : '[No Name]'
    endfunction

    let g:lightline.tab = {
    \    'active': [ 'tabnum', 'filename', 'modified' ],
    \    'inactive': [ 'tabnum', 'filename', 'modified' ]
    \ }

    let g:lightline.tab_component_function = {
    \    'tabnum': 'lightline#tab#tabnum',
    \    'filename': 'LightlineTabFilename',
    \    'modified': 'lightline#tab#modified'
    \ }

    let g:lightline.tabline = {
    \    'left': [ [ 'tabs' ] ],
    \    'right': [ [ 'close' ] ]
    \ }
'''

# linter
[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
  let g:ale_set_highlights = 0
  let g:ale_lint_on_enter = 1
  let g:ale_lint_on_save = 1
  let g:ale_lint_on_text_changed = 0
  let g:ale_sign_column_always = 1
  let g:ale_linters = {
    \ 'ansible': ['ansible-lint'],
    \ 'dockerfile': ['hadolint'],
    \ 'go': ['golint'],
    \ 'json': ['jq'],
    \ 'markdown': ['textlint'],
    \ 'python': ['pyflakes'],
    \ 'vim': ['vint'],
    \ 'yaml': ['yamllint'],
    \ }
  let g:ale_sign_error = 'E'
  let g:ale_sign_warning = 'W'
  let g:ale_echo_msg_error_str = 'E'
  let g:ale_echo_msg_warning_str = 'W'
  let g:ale_echo_msg_format = '[%linter%] %s (%severity%)'
  let g:ale_statusline_format = ['E %d', 'W %d', '']
  let g:ale_open_list = 0
  let g:ale_keep_list_window_open = 0
  let g:ale_javascript_prettier_use_local_config = 1
  let g:ale_set_quickfix = 1
  let g:ale_set_loclist = 0
'''

[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = ['lightline.vim', 'ale']
hook_add = '''
    let g:lightline.component_expand = {
    \    'linter_checking': 'lightline#ale#checking',
    \    'linter_warnings': 'lightline#ale#warnings',
    \    'linter_errors': 'lightline#ale#errors',
    \    'linter_ok': 'lightline#ale#ok',
    \ }
    let g:lightline.component_type = {
    \    'linter_checking': 'left',
    \    'linter_warnings': 'warning',
    \    'linter_errors': 'error',
    \    'linter_ok': 'left',
    \ }
'''

# 左端にgit diff iconを表示
[[plugins]]
repo = 'airblade/vim-gitgutter'

# vim window resize
# usage: <C-x> start, h, j, k, l resize
[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
    let g:winresizer_start_key = '<C-x>'
'''

# vim indent
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
    let g:indent_guides_enable_on_vim_startup = 1
    let g:indent_guides_exclude_filetypes = ['help', 'nerdtree']
    let g:indent_guides_auto_colors = 0
    autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd ctermbg=black
    autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=17
'''

# file selecter
# usage: <C-p>
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

# if, funcのendを補完
[[plugins]]
repo = 'tpope/vim-endwise'

# Comment in/out
# Usage: Visual mode + gc
[[plugins]]
repo = 'tpope/vim-commentary'
