# NERDTree display git status
[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

# NERDTree
# Usage: C-n
[[plugins]]
repo = 'scrooloose/nerdtree'
depends = ['nerdtree-git-plugin']
hook_add = '''
    let g:NERDTreeDirArrows = 1
    let g:NERDTreeDirArrowExpandable  = '→'
    let g:NERDTreeDirArrowCollapsible = '↓'
    let g:NERDTreeShowHidden = 1
    nnoremap <silent> <C-n> :NERDTreeToggle<CR>
'''

# 補完
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
hook_source = '''
  set hidden
  set nobackup
  set nowritebackup

  set cmdheight=2

  let g:coc_global_extensions = [
      \ 'coc-lists',
      \ 'coc-go',
      \ 'coc-json',
      \ 'coc-yaml',
      \ 'coc-python',
      \ 'coc-snippets',
      \ 'coc-eslint',
      \ ]
'''

# snippet
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# snippet
[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

# python
[[plugins]]
repo = 'prabirshrestha/vim-lsp'
on_ft = ['python']

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'vim-syntastic/syntastic'
on_ft = ['python']
hook_post_source = '''
    let g:syntastic_python_checkers = ["flake8"]
'''

# Golang
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']
hook_add = '''
    autocmd FileType go set autowrite

    let g:go_highlight_functions = 1
    let g:go_highlight_methods = 1
    let g:go_highlight_structs = 1
    let g:go_highlight_operators = 1
    let g:go_highlight_fields = 1
    let g:go_highlight_variable_declarations = 1
    let g:go_highlight_variable_assignments = 0
    let g:go_highlight_string_spellcheck = 1
    let g:go_highlight_types = 1
    let g:go_highlight_function_parameters = 1
    let g:go_highlight_extra_types = 1

    let g:go_list_type = "quickfix"

    let g:go_fmt_command = "goimports"

    let g:go_metalinter_autosave = 1
    let g:go_metalinter_autosave_enabled = ["golint"]

    let g:go_term_mode = "split"

    let g:go_addtags_transform = "camelcase"

    let g:go_auto_type_info = 1
    autocmd FileType go set updatetime=100

    let g:go_play_open_browser = 0

    let g:go_auto_sameids = 1
'''

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = ['go']
depends = ['deoplete.nvim']
hook_source = '''
    let g:deoplete#sources#go#gocode_binary = $GOPATH . '/bin/gocode'
'''

# yaml
[[plugins]]
repo = 'stephpy/vim-yaml'
on_ft = ['yml', 'yaml']

# toml
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

# javascript
[[ plugin ]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[ plugin ]]
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript']

# typescript
[[ plugin ]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

# html
[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']

# css
[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css']

# json
[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']
hook_add = '''
    let g:vim_json_syntax_conceal = 0
'''

[[plugins]]
repo = 'rhysd/vim-fixjson'
on_ft = ['json']

# markdown
[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'md']
hook_add = '''
    let g:vim_markdown_folding_disabled = 1
    let g:vim_markdown_codeblock_syntax = 0
'''

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown', 'md']
hook_add = '''
   autocmd BufRead,BufNewFile *.md set filetype=markdown
   let g:previm_open_cmd = 'open -a Google\ Chrome'
'''

# Erlang
[[plugins]]
repo = 'vim-erlang/vim-erlang-runtime'
on_ft = ['erl']

[[plugins]]
repo = 'vim-erlang/vim-erlang-compiler'
on_ft = ['erl']


[[plugins]]
repo = 'vim-erlang/vim-erlang-tags'
on_ft = ['erl']

[[plugins]]
repo = 'vim-erlang/vim-erlang-omnicomplete'
on_ft = ['erl']

# Elixir
[[plugins]]
repo = 'elixir-editors/vim-elixir'
on_ft = ['ex', 'exs']
