# require
[[plugins]]
repo = 'Shougo/dein.vim'

# Icons
[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

# ColorScheme
[[plugins]]
repo = 'EdenEast/nightfox.nvim'

# Statusline
[[plugins]]
repo = 'itchyny/lightline.vim'
depends = ['nightfox.nvim']
hook_add = '''
    function! AbsolutePath()
        let path = expand("%F")
        if path == ""
            return '[No Name]'
        elseif strlen(path) > 32
            return pathshorten(path)
        else
            return path
        endif
    endfunction

    function! LightlineTabFilename(n) abort
        let buflist = tabpagebuflist(a:n)
        let winnr = tabpagewinnr(a:n)
        let _ = pathshorten(expand('#'.buflist[winnr - 1].':f'))
        return _ !=# '' ? _ : '[No Name]'
    endfunction

    let g:lightline = {
    \    'colorscheme': 'nightfox',
    \    'active': {
    \        'left': [
    \            [ 'mode', 'paste' ],
    \            [ 'readonly', 'gitbranch', 'filename', 'modified' ]
    \        ],
    \        'right': [
    \            [ 'lineinfo' ],
    \            [ 'percent' ],
    \            [ 'fileformat', 'fileencoding', 'filetype' ]
    \        ]
    \    },
    \    'component_function': {
    \        'filename': 'AbsolutePath',
    \        'gitbranch': 'FugitiveHead'
    \    },
    \    'separator': {
    \        'left': "\ue0b0",
    \        'right': "\ue0b2"
    \    },
    \    'subseparator': {
    \        'left': "\ue0b1",
    \        'right': "\ue0b3"
    \    },
    \    'mode_map': {
    \        'n' : 'N',
    \        'i' : 'I',
    \        'R' : 'R',
    \        'v' : 'V',
    \        'V' : 'VL',
    \        "\<C-v>": 'VB',
    \        'c' : 'C',
    \        's' : 'S',
    \        'S' : 'SL',
    \        "\<C-s>": 'SB',
    \        't': 'T',
    \    },
    \    'tab': {
    \        'active': [ 'tabnum', 'filename', 'modified' ],
    \        'inactive': [ 'tabnum', 'filename', 'modified' ]
    \    },
    \    'tab_component_function': {
    \        'tabnum': 'lightline#tab#tabnum',
    \        'filename': 'LightlineTabFilename',
    \        'modified': 'lightline#tab#modified'
    \    },
    \    'tabline': {
    \        'left': [ [ 'tabs' ] ],
    \        'right': [ [ 'close' ] ]
    \    }
    \ }
'''

# Auto close parentheses
[[plugins]]
repo = 'cohama/lexima.vim'

# Coloring parentheses
[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
    let g:rainbow_active = 1
'''

# vim 非同期処理
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# LSP
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
on_i = 1
merged = '0'
hook_source = '''
    set hidden
    set nobackup
    set nowritebackup

    set cmdheight=2

    let g:coc_global_extensions = [
    \    'coc-lists',
    \    'coc-git',
    \    'coc-explorer',
    \    'coc-snippets',
    \    'coc-json',
    \    'coc-yaml',
    \    'coc-elixir',
    \    'coc-go',
    \    'coc-rls',
    \    'coc-docker',
    \    'coc-markdownlint',
    \    'coc-prettier',
    \    'coc-tsserver',
    \    'coc-eslint',
    \    'coc-jedi',
    \    'coc-diagnostic',
    \    'coc-vimlsp',
    \ ]
'''

# fzf
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
merged = 0

[[plugins]]
repo = 'tpope/vim-fugitive'

# 左端に git diff icon を表示
[[plugins]]
repo = 'airblade/vim-gitgutter'

# vim window resize
# usage: <C-x> start, h, j, k, l resize
[[plugins]]
repo = 'simeji/winresizer'
hook_add = '''
    let g:winresizer_start_key = '<C-x>'
'''

# vim indent
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
    let g:indent_guides_enable_on_vim_startup = 1
    let g:indent_guides_exclude_filetypes = ['help', 'coc-explorer']
    let g:indent_guides_auto_colors = 0

    " autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd ctermbg=black
    " autocmd VimEnter,Colorscheme * :hi IndentGuidesEven ctermbg=17
'''

# Comment in/out
# Usage: Visual mode + gc
[[plugins]]
repo = 'tpope/vim-commentary'

# Use DeepL translate
[[plugins]]
repo = 'sfuruya0612/vim-translate'

# Use GitHub Copilot
[[plugins]]
repo = 'github/copilot.vim'
hook_add = '''
    let g:copilot_node_command = "/opt/homebrew/bin/node"
    let g:copilot_filetypes = {
    \   '*': v:false,
    \   'javascript': v:true,
    \   'typescript': v:true,
    \   'typescriptreact': v:true,
    \   'go': v:true,
    \   'python': v:true,
    \   'markdown': v:true,
    \   'vim': v:true,
    \   'elixir': v:true,
    \   'rust': v:true,
    \   'dockerfile': v:true,
    \ }
'''

# telescope optional dependencies
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'

# telescope and ChatGPT required dependencies
[[plugins]]
repo = 'nvim-lua/plenary.nvim'

# ChatGPT.nvim requited dependencies
[[plugins]]
repo = 'MunifTanjim/nui.nvim'

# fuzzy finder
[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
rev = '0.1.1'
hook_add = '''
    " Using Lua functions
    nmap <silent> ff <cmd>lua require('telescope.builtin').find_files()<cr>
    nmap <silent> fg <cmd>lua require('telescope.builtin').live_grep()<cr>
    nmap <silent> fb <cmd>lua require('telescope.builtin').buffers()<cr>
    nmap <silent> fh <cmd>lua require('telescope.builtin').help_tags()<cr>

lua <<EOF
require('telescope').setup{
    defaults = {
        mappings = {
            i = {
                ["<C-s>"] = require('telescope.actions').file_split,
                ["<C-v>"] = require('telescope.actions').file_vsplit
            }
        }
    }
}
EOF
'''

# Use ChatGPT
[[plugins]]
repo = 'jackMort/ChatGPT.nvim'
depends = ['nui.nvim', 'plenary.nvim', 'telescope.nvim']
hook_add = '''
lua <<EOF
require('chatgpt').setup()
EOF
'''
