"           _
"    __   _(_)_ __ ___  _ __ ___
"    \ \ / / | '_ ` _ \| '__/ __|
"     \ V /| | | | | | | | | (__
"    (_)_/ |_|_| |_| |_|_|  \___|
"
filetype plugin indent off

" Encoding settings -------------------
set encoding=utf-8
set fileformats=unix,dos,mac
scriptencoding utf-8

" General Settings --------------------
set updatetime=250
set number
set ttyfast
set noswapfile
" 括弧やfunctionで[%]ジャンプ
source $VIMRUNTIME/macros/matchit.vim

set whichwrap=b,s,h,l,<,>,[,],~

nnoremap j gj
nnoremap k gk
nnoremap <C-a> ^
nnoremap <C-e> $

set clipboard+=unnamed

noremap <leader>u :w<Home>silent <End> !urlview<CR>

imap <S-CR> <End><CR>
imap <C-S-CR> <Up><End><CR>
nnoremap <S-CR> mzo<ESC>`z
nnoremap <C-S-CR> mzO<ESC>`z

" Start Dein Settings -----------------
let s:dein_dir = $HOME . '/.vim/cache'
if has('nvim')
    let s:dein_dir = $HOME . '/.config/nvim/cache'
endif
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'

if &runtimepath !~# '/dein.vim'
    if !isdirectory(s:dein_repo_dir)
        execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
    endif

	execute 'set runtimepath^=' . fnamemodify(s:dein_repo_dir, ':p')
endif

if dein#load_state(s:dein_dir)
    call dein#begin(s:dein_dir)

    let g:dein_plugin_dir = expand($HOME . '/dotfiles/roles/vim/files/rc')
    call dein#load_toml(g:dein_plugin_dir . '/dein.toml', {'lazy': 0})
    call dein#load_toml(g:dein_plugin_dir . '/dein_lazy.toml', {'lazy': 1})

    call dein#end()
    call dein#save_state()
endif

if dein#check_install()
    call dein#install()
endif
" End Dein Settings --------------------

" Setting the Status & Tab Line -------------
set laststatus=2
set noshowmode
set showtabline=2

" Tab & Indent Setting ----------------
set expandtab
set tabstop=4
set softtabstop=2
set autoindent
set smartindent
set shiftwidth=4

" Highlight & Search Settings ------------------
set showmatch
set cursorline
" Highlight on Search Toggle
set hlsearch
    nnoremap <silent><Esc><Esc> :<C-u>set nohlsearch!<CR>
augroup HighlightTrailingSpaces
    autocmd!
    autocmd VimEnter,WinEnter,ColorScheme * highlight TrailingSpaces term=underline guibg=Red ctermbg=Red
    autocmd VimEnter,WinEnter * match TrailingSpaces /\s\+$/
augroup END
set incsearch
set ignorecase
set smartcase

" Setting the Color Scheme ------------
set termguicolors
let $NVIM_TUI_ENABLE_TRUE_COLOR=1
colorscheme night-owl

" vimdiff Color ------------
autocmd VimEnter,WinEnter,ColorScheme * highlight DiffAdd    cterm=bold ctermfg=DarkMagenta ctermbg=0x002b36 gui=none guifg=bg guibg=Red
autocmd VimEnter,WinEnter,ColorScheme * highlight DiffDelete cterm=bold ctermfg=Red         ctermbg=0x002b36 gui=none guifg=bg guibg=Red
autocmd VimEnter,WinEnter,ColorScheme * highlight DiffChange cterm=bold ctermfg=DarkMagenta ctermbg=0x002b36 gui=none guifg=bg guibg=Red
autocmd VimEnter,WinEnter,ColorScheme * highlight DiffText   cterm=bold ctermfg=black       ctermbg=Red      gui=none guifg=bg guibg=Red

filetype plugin indent on
