---
- name: Make ~/.tmux/plugins directory
  file:
    path: "{{ ansible_env.HOME }}/.tmux/plugins/"
    state: directory

- name: Clone tmux plugin repo
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"

- name: Symbolic link ~/dotfiles/roles/tmux/files/tmux.conf -> ~/.tmux.conf
  file:
    src: "{{ ansible_env.HOME }}/dotfiles/roles/tmux/files/tmux.conf"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    state: link
    force: yes
