---
- name: Create ~/.tmux/plugins directory
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ ansible_env.HOME }}/.tmux/tmp/"
    - "{{ ansible_env.HOME }}/.tmux/plugins/"

- name: Clone tmux plugin repo
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"

- name: Set configuration file
  template:
    src: "tmux.conf.j2"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
