---
- name: Create ~/.tmux/plugins directory
  file:
    path: "{{ ansible_env.HOME }}/.tmux/plugins/"
    state: directory

- name: Clone tmux plugin repo
  git:
    repo: "https://github.com/tmux-plugins/tpm"
    dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"

- name: Set configuration file
  template:
    src: "tmux.conf.j2"
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
