---
- name: Setting NSGlobalDomain
  osx_defaults:
    domain: NSGlobalDomain
    key: "{{ global_setting_item.key }}"
    type: "{{ global_setting_item.type }}"
    value: "{{ global_setting_item.value }}"
    state: present
  with_items: "{{ global_settings }}"
  loop_control:
    loop_var: global_setting_item
