---
- name: Setting NSGlobalDomain
  osx_defaults:
    domain: NSGlobalDomain
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ global_settings }}"
