---
- name: Setting Clock
  osx_defaults:
    domain: com.apple.menuextra.clock
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ clock_settings }}"

- name: Setting Battery
  osx_defaults:
    domain: com.apple.menuextra.battery
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ battery_settings }}"
