---
- name: Setting Safari.app
  osx_defaults:
    domain: com.apple.Safari
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ safari_settings }}"
  notify: restart safari
