---
- name: Create apps and project directory
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  loop:
    - "apps"
    - "works"
    - "fonts"
    - "tmp"

- name: Clone fonts repo
  git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    depth: 1
  loop:
    - repo: "https://github.com/powerline/fonts.git"
      dest: "{{ ansible_env.HOME }}/fonts/powerline"

- name: Install powerline fonts
  shell: >
    {{ ansible_env.HOME }}/fonts/powerline/install.sh
