---
- name: Create apps and project directory
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  loop:
    - "apps"
    - "works"
    - "tmp"

- name: Clone powerline fonts repo
  git:
    repo: "https://github.com/powerline/fonts.git"
    dest: "{{ ansible_env.HOME }}/fonts"
    depth: 1

- name: Install powerline fonts
  shell: >
    {{ ansible_env.HOME }}/fonts/install.sh

- name: Remove powerline fonts repo
  file:
    path: "{{ ansible_env.HOME }}/fonts/"
    state: absent
