---
- name: Create apps and project directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  loop:
    - apps
    - works
    - fonts
    - tmp

- name: Clone fonts repo
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ item.dest }}"
    depth: 1
  loop:
    - repo: "https://github.com/powerline/fonts.git"
      dest: "{{ ansible_env.HOME }}/fonts/powerline"

- name: Install powerline fonts
  ansible.builtin.shell:
    cmd: |
      {{ ansible_env.HOME }}/fonts/powerline/install.sh
