---
- name: Create .config/nvim directory
  file:
    path: "{{ ansible_env.HOME }}/.config/nvim"
    state: directory

- name: Install neovim from pip3
  pip:
    name: neovim
    executable: pip3
    state: latest

- name: Symbolic link vimrc to neovim init.vim
  file:
    src: "{{ ansible_env.HOME }}/dotfiles/roles/vim/files/vimrc"
    dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"
    state: link
    force: yes
