---
- name: Unlink config file
  ansible.builtin.file:
    path: "{{ item }} "
    state: absent
  loop:
    - "{{ ansible_env.HOME }}/.config/nvim/coc-settings.json"
    - "{{ ansible_env.HOME }}/.config/nvim/init.vim"
    - "{{ ansible_env.HOME }}/.config/nvim/dein.toml"
    - "{{ ansible_env.HOME }}/.config/nvim/dein_lazy.toml"

- name: Create config files directory
  ansible.builtin.file:
    path: "{{ item }} "
    state: directory
  loop:
    - "{{ ansible_env.HOME }}/.config/nvim"

- name: Install neovim from pip3
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: "/opt/homebrew/bin/pip3"
    state: latest
  loop:
    - neovim
    - pynvim
    - jedi-language-server
    - flake8
    - black

- name: Install neovim from yarn
  community.general.yarn:
    name: "{{ item }}"
    executable: "/opt/homebrew/bin/yarn"
    global: true
    state: present
  loop:
    - neovim
    - bash-language-server
    - vim-language-server

- name: Symbolic link config files
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    force: true
  loop:
    - src: "{{ ansible_env.HOME }}/dotfiles/roles/vim/files/coc-settings.json"
      dest: "{{ ansible_env.HOME }}/.config/nvim/coc-settings.json"
    - src: "{{ ansible_env.HOME }}/dotfiles/roles/vim/files/vimrc"
      dest: "{{ ansible_env.HOME }}/.config/nvim/init.vim"
    - src: "{{ ansible_env.HOME }}/dotfiles/roles/vim/files/dein.toml"
      dest: "{{ ansible_env.HOME }}/.config/nvim/dein.toml"
    - src: "{{ ansible_env.HOME }}/dotfiles/roles/vim/files/dein_lazy.toml"
      dest: "{{ ansible_env.HOME }}/.config/nvim/dein_lazy.toml"
