---
- name: Create config directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ ansible_env.HOME }}/.config/nvim"
    - "{{ ansible_env.HOME }}/.config/nvim/lua"

- name: Install neovim from pip3
  ansible.builtin.pip:
    name: "{{ item }}"
    executable: "/opt/homebrew/bin/pip3"
    extra_args: "--break-system-package"
    state: latest
  loop:
    - neovim
    # - pynvim
    # - ruff-lsp

- name: Install neovim from yarn
  community.general.yarn:
    name: "{{ item }}"
    executable: "/opt/homebrew/bin/yarn"
    global: true
    state: present
  loop:
    - neovim
    # - bash-language-server
    # - vim-language-server
  failed_when: false

- name: Unlink config files
  ansible.builtin.file:
    path: "{{ vim_init_dest_dir }}{{ item }} "
    state: absent
  loop: "{{ vim_config_files }}"

- name: Unlink lua files
  ansible.builtin.file:
    path: "{{ vim_lua_dest_dir }}{{ item }} "
    state: absent
  loop: "{{ vim_lua_files }}"

- name: Symbolic link config files
  ansible.builtin.file:
    src: "{{ vim_src_dir }}{{ item }}"
    dest: "{{ vim_init_dest_dir }}{{ item }}"
    state: link
    force: true
  loop: "{{ vim_config_files }}"

- name: Symbolic link lua files
  ansible.builtin.file:
    src: "{{ vim_src_dir }}{{ item }}"
    dest: "{{ vim_lua_dest_dir }}{{ item }}"
    state: link
    force: true
  loop: "{{ vim_lua_files }}"
