---
- name: Create alacritty config directory
  ansible.builtin.file:
    path: "{{ dest_config_dir }}"
    state: directory

- name: Set additional config files
  ansible.builtin.file:
    src: "{{ src_config_dir }}/{{ item }}"
    dest: "{{ dest_config_dir }}/{{ item }}"
    state: link
    force: true
  loop:
    - colors.toml
    - cursor.toml
    - font.toml
    - mouse.toml
    - scrolling.toml
    - selection.toml
    - window.toml

- name: Set main config file
  ansible.builtin.template:
    src: "alacritty.toml.j2"
    dest: "{{ dest_config_dir }}/alacritty.toml"
