---
- name: Create alacritty config directory
  file:
    path: "{{ ansible_env.HOME }}/.config/alacritty"
    state: directory

- name: Set configuration file
  template:
    src: "alacritty.yml.j2"
    dest: "{{ ansible_env.HOME }}/.config/alacritty/alacritty.yml"
