---
- name: Setting dock
  community.general.osx_defaults:
    domain: com.apple.dock
    key: "{{ osx_dock_setting_item.key }}"
    type: "{{ osx_dock_setting_item.type }}"
    value: "{{ osx_dock_setting_item.value }}"
    state: present
  loop: "{{ osx_dock_settings }}"
  loop_control:
    loop_var: osx_dock_setting_item
  notify: restart dock
