---
- name: Setting dock
  osx_defaults:
    domain: com.apple.dock
    key: "{{ dock_setting_item.key }}"
    type: "{{ dock_setting_item.type }}"
    value: "{{ dock_setting_item.value }}"
    state: present
  loop: "{{ dock_settings }}"
  loop_control:
    loop_var: dock_setting_item
  notify: restart dock
