---
- name: Setting Finder
  community.general.osx_defaults:
    domain: com.apple.finder
    key: "{{ osx_finder_setting_item.key }}"
    type: "{{ osx_finder_setting_item.type }}"
    value: "{{ osx_finder_setting_item.value }}"
    state: present
  loop: "{{ osx_finder_settings }}"
  loop_control:
    loop_var: osx_finder_setting_item
  notify: restart finder
