---
- name: Setting NSGlobalDomain
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: "{{ osx_global_setting_item.key }}"
    type: "{{ osx_global_setting_item.type }}"
    value: "{{ osx_global_setting_item.value }}"
    state: present
  loop: "{{ osx_global_settings }}"
  loop_control:
    loop_var: osx_global_setting_item
