---
- name: Setting Keyboard
  community.general.osx_defaults:
    domain: com.apple.inputmethod.Kotoeri
    key: "{{ osx_keyboard_setting_item.key }}"
    type: "{{ osx_keyboard_setting_item.type }}"
    value: "{{ osx_keyboard_setting_item.value }}"
    state: present
  loop: "{{ osx_keyboard_settings }}"
  loop_control:
    loop_var: osx_keyboard_setting_item
