---
- name: Settings OSX
  include_tasks: "{{ item }}"
  loop:
    - global.yml
    - dock.yml
    - safari.yml
    - finder.yml
    - menuextra.yml
    - trackpad.yml
    - keyboard.yml
    # - universalaccess.yml
