---
- name: Setting Clock
  community.general.osx_defaults:
    domain: com.apple.menuextra.clock
    key: "{{ osx_clock_setting_item.key }}"
    type: "{{ osx_clock_setting_item.type }}"
    value: "{{ osx_clock_setting_item.value }}"
    state: present
  loop: "{{ osx_clock_settings }}"
  loop_control:
    loop_var: osx_clock_setting_item

- name: Setting Battery
  community.general.osx_defaults:
    domain: com.apple.menuextra.battery
    key: "{{ osx_battery_setting_item.key }}"
    type: "{{ osx_battery_setting_item.type }}"
    value: "{{ osx_battery_setting_item.value }}"
    state: present
  loop: "{{ osx_battery_settings }}"
  loop_control:
    loop_var: osx_battery_setting_item
