---
- name: Setting Clock
  osx_defaults:
    domain: com.apple.menuextra.clock
    key: "{{ clock_setting_item.key }}"
    type: "{{ clock_setting_item.type }}"
    value: "{{ clock_setting_item.value }}"
    state: present
  loop: "{{ clock_settings }}"
  loop_control:
    loop_var: clock_setting_item

- name: Setting Battery
  osx_defaults:
    domain: com.apple.menuextra.battery
    key: "{{ battery_setting_item.key }}"
    type: "{{ battery_setting_item.type }}"
    value: "{{ battery_setting_item.value }}"
    state: present
  loop: "{{ battery_settings }}"
  loop_control:
    loop_var: battery_setting_item
