---
- name: Setting Safari.app
  community.general.osx_defaults:
    domain: com.apple.Safari
    key: "{{ osx_safari_setting_item.key }}"
    type: "{{ osx_safari_setting_item.type }}"
    value: "{{ osx_safari_setting_item.value }}"
    state: present
  loop: "{{ osx_safari_settings }}"
  loop_control:
    loop_var: osx_safari_setting_item
  notify: restart safari
