---
- name: Setting Safari.app
  osx_defaults:
    domain: com.apple.Safari
    key: "{{ safari_setting_item.key }}"
    type: "{{ safari_setting_item.type }}"
    value: "{{ safari_setting_item.value }}"
    state: present
  loop: "{{ safari_settings }}"
  loop_control:
    loop_var: safari_setting_item
  notify: restart safari
