---
- name: Setting trackpad
  community.general.osx_defaults:
    domain: com.apple.AppleMultitouchTrackpad
    key: "{{ osx_trackpad_setting_item.key }}"
    type: "{{ osx_trackpad_setting_item.type }}"
    value: "{{ osx_trackpad_setting_item.value }}"
    state: present
  loop: "{{ osx_trackpad_settings }}"
  loop_control:
    loop_var: osx_trackpad_setting_item
