---
- name: Setting Universalaccess
  community.general.osx_defaults:
    domain: com.apple.universalaccess
    key: "{{ osx_universalaccess_setting_item.key }}"
    type: "{{ osx_universalaccess_setting_item.type }}"
    value: "{{ osx_universalaccess_setting_item.value }}"
    state: present
  loop: "{{ osx_universalaccess_settings }}"
  loop_control:
    loop_var: osx_universalaccess_setting_item
