---
- name: Setting Universalaccess
  osx_defaults:
    domain: com.apple.universalaccess
    key: "{{ universalaccess_setting_item.key }}"
    type: "{{ universalaccess_setting_item.type }}"
    value: "{{ universalaccess_setting_item.value }}"
    state: present
  loop: "{{ universalaccess_settings }}"
  loop_control:
    loop_var: universalaccess_setting_item
