---
- name: Create ~/.config directories
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/zellij"
    state: directory

- name: Unlink config file
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/zellij/config.kdl"
    state: absent

- name: Symbolic link config file
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/dotfiles/roles/zellij/files/config.kdl"
    dest: "{{ ansible_env.HOME }}/.config/zellij/config.kdl"
    state: link
    force: true
