---
- name: Clone powerline fonts repo
  git:
    repo: "https://github.com/powerline/fonts.git"
    dest: "{{ ansible_env.HOME }}/fonts"
    depth: 1

- name: Install powerline font
  shell: "{{ ansible_env.HOME }}/fonts/install.sh"
